### save staff
POST http://localhost:8080/staff/add
Content-Type: application/json

{
  "staffName": "Jesii2",
  "staffEmail": "jessi2@gmail.com",
  "staffPass": "jessi"
}




### update staff
PUT http://localhost:8080/staff/update?staffId=Staff:d4ac8e76-9d10-481f-bdbb-b10d0a61db8c
Content-Type: application/json
Authorization: Basic admin@gmail.com admin

{
  "staffName": "UpdateOnlyUser",
  "staffEmail": "updateonlyuser@gmail.com",
  "staffPass": "updateonlyuser"
}


### get all staff
GET http://localhost:8080/staff/all

### delete staff
DELETE http://localhost:8080/staff/del?staffId=Staff:d1c50018-629e-41af-b957-885df3bad914
Authorization: Basic admin@gmail.com admin

### staff login
POST http://localhost:8080/staff/login
Content-Type: application/json

{
  "staffEmail": "denver@gmail.com",
  "staffPass": "denver"
}

### ADD EVENT
POST http://localhost:8080/event/addEvent
Authorization: Basic testemp@gmail.com testemp
Content-Type: application/json

{
  "eventName": "TestEvent2",
  "eventVenue": "TestLocation2",
  "eventDate": "05-12-2024 03:35 PM",
  "eventDescription": "TestDesc2"
}

### Get Events
GET http://localhost:8080/event/getEvent
Authorization: Basic testemp@gmail.com testemp




### create meeting
POST http://localhost:8080/meet/create
Authorization: Basic testemp@gmail.com testemp
Content-Type: application/json

{
  "meetingName": "saran raj",
  "meetingDescription": "sdvsdvsv",
  "empIdList": [
    "Staff:75d0aae1-0e3a-4049-bcaf-4589981d2c0b"
  ],
  "meetingDateTime": "2025-10-10 09:09 PM",
  "meetingLink": "https://meet.google.com/cub-ubor-mjy",
  "meetingOwner": "test"
}


### cancel meeting
POST http://localhost:8080/meet/cancel?meetingId=Meeting:d75cdf9d-8b13-4443-914a-8a39cf591c4c
Authorization: Basic testemp@gmail.com testemp
Content-Type: application/json



### getActiveMeetings
GET http://localhost:8080/meet/active
Authorization: Basic testemp@gmail.com testemp
Content-Type: application/json

